# train options
seed: 42
batch_size: 124
workers: 16
start_epoch: 0
epochs: 100
dataset: "Fashion200K"
root: "/$HOME/thesis/data/Fashion200K/all/pictures_only"

# model options
resnet: "resnet50"
normalize: True
projection_dim: 64

# loss options
optimizer: "Adam"
weight_decay: 1.0e-6
temperature: 0.5

# reload options
model_path: "logs/0"
epoch_num: 100

# mixed-precision training
fp16: False
fp16_opt_level: O2


# logistic regression options
logistic_batch_size: 256
logistic_epochs: 100
